# pre-commit configuration file
# You may automatically run pre-commit when committing
# by installing hooks as follows:
# pre-commit install
# pre-commit install --hook-type commit-msg
---
fail_fast: false
default_language_version:
  python: python3
exclude: /ext/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.29.0
    hooks:
      - id: yapf
  - repo: https://github.com/PyCQA/pylint
    rev: v2.8.2
    hooks:
      - id: pylint
        args:
          [
            "--disable=import-error,no-name-in-module,duplicate-code",
          ]
  - repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
    rev: v0.6.9
    hooks:
      - id: cmake-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        types_or: [c++, c]
  - repo: https://github.com/cpplint/cpplint
    rev: 1.5.5
    hooks:
      - id: cpplint
        files: \.(h|hh|hpp|hxx|h|c|cc|cpp|cxx|c)$
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
      - id: gitlint-ci # hook for CI environments
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    - id: bandit
